language: python
python:
  - '3.8'

before_script:
  - pip install -r requirements.txt

branches:
  only:
    - staging

env: DJANGO_SETTINGS_MODULE="p8Nutella.settings.travis"

services:
  - postgresql

script:
  - python3 manage.py test