# Generated by Django 3.2.13 on 2022-11-25 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def get_conversion_function(collation, character_set='utf8mb4'):
    """
    Returns a function that sets the given *collation* and *character_set*.
    Args:
        collation: e.g. `utf8_general_cs`, `utf8_general_ci` or `utf8_bin`…
        character_set: e.g. `utf8`, `latin1`…
    """

    def alter_collation_from_migration(apps, schema_editor):
        """
        Sets *collation* and *character_set* for a database and its tables.
        Also converts data in the tables if necessary.
        """
        with schema_editor.connection.cursor() as cursor:
            # set for database
            print('Altering database…')
            cursor.execute(
                f'ALTER DATABASE CHARACTER SET'
                f' {character_set} COLLATE {collation};'
            )
            # set for tables (and convert data)
            cursor.execute(
                'SHOW TABLES;'
            )
            for table, in cursor.fetchall():
                print(f'Altering table `{table}`…')
                cursor.execute(
                    f'ALTER TABLE {table} CONVERT TO CHARACTER '
                    f'SET {character_set} COLLATE {collation}'
                )

    return alter_collation_from_migration


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('brands', models.CharField(max_length=150)),
                ('barcode', models.CharField(max_length=13, unique=True)),
                ('nutriscore', models.CharField(max_length=1)),
                ('url', models.URLField()),
                ('image_url', models.URLField()),
                ('image_small_url', models.URLField()),
                ('energy_100g', models.FloatField(default=0, null=True)),
                ('sugars_100g', models.FloatField(default=0, null=True)),
                ('sodium_100g', models.FloatField(default=0, null=True)),
                ('fat_100g', models.FloatField(default=0, null=True)),
                ('salt_100g', models.FloatField(default=0, null=True)),
                ('categories', models.ManyToManyField(to='search.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID')),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='favorite_product', to='search.product')),
                ('substitute', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='favorite_substitute', to='search.product')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='favorite_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        # migrations.RunPython(get_conversion_function('utf8mb4_bin'))
    ]
